version: "3"

services:
  web:
    container_name: fuxiqueira-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8080:8080"
